Chore/update release tittle
1f349/vaultwarden-binary pull request #2
Opened 2024-10-28 06:42 UTC by nalakawula

2024-10-28 07:36 UTC, mrmelon54 commented
Interesting...

2024-11-05 18:38 UTC, mrmelon54 commented
Why was this closed?

2024-11-13 07:58 UTC, nalakawula commented
initially, i want to PR with small changes for easier review.

Reopen now, thanks.

2025-01-09 13:19 UTC, mrmelon54 requested changes
Looks pretty good, just update the release URLs for this repo

2025-01-09 13:19 UTC, mrmelon54 commented on README.md
> +1. Download the binary from the [releases page](https://github.com/nalakawula/vaultwarden-binary/releases).
This should be changed back to the 1f349 link for this PR

2025-01-09 13:19 UTC, mrmelon54 commented on README.md
> +You can download the latest version of the Vaultwarden binary for your platform from the [releases page](https://github.com/nalakawula/vaultwarden-binary/releases).
This should be changed back to the 1f349 link for this PR

2025-01-15 12:35 UTC, nalakawula commented
Link updated

2025-01-27 23:10 UTC, merged